/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package healthswift.pkgcase.study;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author Kheymp
 */
public class PanelDoctorRegistration extends javax.swing.JPanel {
    DoctorRegistrationForm doctorRegistrationForm = new DoctorRegistrationForm();
    /**
     * Creates new form PanelDoctorRegistration
     */
    public PanelDoctorRegistration() {
        this.setBounds(0, 0, 800, 600);
        this.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        pnlSignIn = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtEnterDoctorBDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDocGender = new javax.swing.JComboBox<>();
        txtEnterDoctorLName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtEnterDoctorFName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        timePicker = new com.raven.swing.TimePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblMonTime = new javax.swing.JLabel();
        lblTueTime = new javax.swing.JLabel();
        lblWedTime = new javax.swing.JLabel();
        lblThurTime = new javax.swing.JLabel();
        lblFriTime = new javax.swing.JLabel();
        lblSatTime = new javax.swing.JLabel();
        txtEnterDoctorPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmitDoctorReg = new javax.swing.JButton();
        btnSetSched = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDayReg = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDoctorSpecialty = new javax.swing.JComboBox<>();
        txtLicenseNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEnterDoctorNo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtEnterDoctorEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtEndTime = new javax.swing.JTextField();
        txtStartTime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBackToSignIn = new javax.swing.JButton();

        dateChooser.setDateFormat("yyyy-MM-dd");
        dateChooser.setTextRefernce(txtEnterDoctorBDate);

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSignIn.setBackground(new java.awt.Color(51, 102, 255));
        pnlSignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(txtEnterDoctorBDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 130, -1));

        jLabel8.setText("Birth date:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        jLabel12.setText("Gender:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        txtDocGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel4.add(txtDocGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 130, -1));
        jPanel4.add(txtEnterDoctorLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 130, -1));

        jLabel7.setText("Last name:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, -1));

        jLabel21.setText("First name:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, -1));
        jPanel4.add(txtEnterDoctorFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel16.setText("Basic Information");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 480));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timePicker.set24hourMode(true);
        jPanel3.add(timePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Tuesday");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Wednesday");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Thursday");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Friday");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setText("Saturday");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel26.setForeground(new java.awt.Color(0, 0, 204));
        jLabel26.setText("Monday");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblMonTime.setForeground(new java.awt.Color(0, 0, 204));
        lblMonTime.setText("00:00");
        jPanel2.add(lblMonTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, -1));

        lblTueTime.setForeground(new java.awt.Color(0, 0, 204));
        lblTueTime.setText("00:00");
        jPanel2.add(lblTueTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, -1));

        lblWedTime.setForeground(new java.awt.Color(0, 0, 204));
        lblWedTime.setText("00:00");
        jPanel2.add(lblWedTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        lblThurTime.setForeground(new java.awt.Color(0, 0, 204));
        lblThurTime.setText("00:00");
        jPanel2.add(lblThurTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, -1));

        lblFriTime.setForeground(new java.awt.Color(0, 0, 204));
        lblFriTime.setText("00:00");
        jPanel2.add(lblFriTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 130, -1));

        lblSatTime.setForeground(new java.awt.Color(0, 0, 204));
        lblSatTime.setText("00:00");
        jPanel2.add(lblSatTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 130, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 230, 140));
        jPanel3.add(txtEnterDoctorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 130, -1));

        jLabel4.setText("Password:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 60, -1));

        btnSubmitDoctorReg.setBackground(new java.awt.Color(153, 255, 153));
        btnSubmitDoctorReg.setText("Submit");
        btnSubmitDoctorReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitDoctorRegActionPerformed(evt);
            }
        });
        jPanel3.add(btnSubmitDoctorReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        btnSetSched.setText("Set");
        btnSetSched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetSchedActionPerformed(evt);
            }
        });
        jPanel3.add(btnSetSched, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 60, -1));

        jLabel13.setText("To:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 30, -1));

        jLabel10.setText("From:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 50, -1));

        jLabel6.setText("Day:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 40, -1));

        txtDayReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));
        txtDayReg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtDayRegItemStateChanged(evt);
            }
        });
        jPanel3.add(txtDayReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Clinic Schedule");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel11.setText("Summary: ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel19.setText("Specialty Information");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setText("Speciality:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, -1));

        txtDoctorSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Medicine", "Internal Medicine", "Primary Care", "Pediatrics", "Family Medicine", "Obstetrics and Gynecology", "Preventative Medicine", "General Surgery", "Public Health", "Occupational and Industrial Medicine" }));
        txtDoctorSpecialty.setMinimumSize(new java.awt.Dimension(64, 22));
        jPanel3.add(txtDoctorSpecialty, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 160, -1));
        jPanel3.add(txtLicenseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, -1));

        jLabel3.setText("License No.:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));
        jPanel3.add(txtEnterDoctorNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, -1));

        jLabel23.setText("Contact #:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 70, -1));

        jLabel22.setText("Email:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 50, -1));

        txtEnterDoctorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterDoctorEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtEnterDoctorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 130, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel20.setText("Contact Information");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        txtEndTime.setEditable(false);
        txtEndTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEndTimeMouseClicked(evt);
            }
        });
        txtEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndTimeActionPerformed(evt);
            }
        });
        jPanel3.add(txtEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 80, -1));

        txtStartTime.setEditable(false);
        txtStartTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStartTimeMouseClicked(evt);
            }
        });
        txtStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartTimeActionPerformed(evt);
            }
        });
        jPanel3.add(txtStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 80, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 500, 480));

        pnlSignIn.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 780, 480));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor Registration");
        jLabel1.setToolTipText("");
        pnlSignIn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 800, -1));

        btnBackToSignIn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBackToSignIn.setText("Go Back");
        btnBackToSignIn.setToolTipText("");
        btnBackToSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToSignInActionPerformed(evt);
            }
        });
        pnlSignIn.add(btnBackToSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        add(pnlSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitDoctorRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitDoctorRegActionPerformed

        if (txtEnterDoctorEmail.getText().equals("") || txtEnterDoctorPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter valid name and password.", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtEnterDoctorFName.getText().equals("") || txtEnterDoctorLName.getText().equals("") || txtLicenseNo.getText().equals("") || txtEnterDoctorNo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out all fields.", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            doctorRegistrationForm.setEmail(txtEnterDoctorEmail.getText());
            doctorRegistrationForm.setFullName(txtEnterDoctorFName.getText() + " " + txtEnterDoctorLName.getText());
            doctorRegistrationForm.setGender(txtDocGender.getSelectedItem().toString());
            doctorRegistrationForm.setSpecialty(txtDoctorSpecialty.getSelectedItem().toString());
            doctorRegistrationForm.setBirthDate(Date.valueOf(txtEnterDoctorBDate.getText()));
            doctorRegistrationForm.setLicenseNo(txtLicenseNo.getText());
            doctorRegistrationForm.setContactNo(txtEnterDoctorNo.getText());
            doctorRegistrationForm.setPassword(HealthSwift.encrypt(txtEnterDoctorPassword.getText()));
            
            try {
                
                String insert = "INSERT INTO doctor(email, name, gender, birthdate, specialty, licenseNo, contact, password, mondayStart, mondayEnd, tuesdayStart, tuesdayEnd, wednesdayStart, wednesdayEnd, thursdayStart, thursdayEnd, fridayStart, fridayEnd, saturdayStart, saturdayEnd) " + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/healthswift?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "password");
                java.sql.PreparedStatement prestate = connection.prepareStatement(insert);
                
                String newAppointmentTableName = doctorRegistrationForm.getLicenseNo() + "appointment";
                
                
                String sql = "CREATE TABLE " + newAppointmentTableName + " (email VARCHAR(50) PRIMARY KEY, name VARCHAR(50), timeStart TIME, timeEnd TIME, date DATE)";

                // Create a Statement object
                java.sql.Statement statement = connection.createStatement();

                // Execute SQL query to create table
                statement.executeUpdate(sql);

                //System.out.println("Table " + newAppointmentTableName + " created successfully.");

                // Close resources
                //statement.close();
                //connection.close();
                
                prestate.setString(1, doctorRegistrationForm.getEmail());
                prestate.setString(2, doctorRegistrationForm.getFullName());
                prestate.setString(3, doctorRegistrationForm.getGender());
                prestate.setDate(4, doctorRegistrationForm.getBirthDate());
                prestate.setString(5, doctorRegistrationForm.getSpecialty());
                prestate.setString(6, doctorRegistrationForm.getLicenseNo());
                prestate.setString(7, doctorRegistrationForm.getContactNo());
                prestate.setString(8, doctorRegistrationForm.getPassword());
                prestate.setTime(9, java.sql.Time.valueOf(doctorRegistrationForm.monTimeStart));
                prestate.setTime(10, java.sql.Time.valueOf(doctorRegistrationForm.monTimeEnd));
                prestate.setTime(11, java.sql.Time.valueOf(doctorRegistrationForm.tueTimeStart));
                prestate.setTime(12, java.sql.Time.valueOf(doctorRegistrationForm.tueTimeEnd));
                prestate.setTime(13, java.sql.Time.valueOf(doctorRegistrationForm.wedTimeStart));
                prestate.setTime(14, java.sql.Time.valueOf(doctorRegistrationForm.wedTimeEnd));
                prestate.setTime(15, java.sql.Time.valueOf(doctorRegistrationForm.thurTimeStart));
                prestate.setTime(16, java.sql.Time.valueOf(doctorRegistrationForm.thurTimeEnd));
                prestate.setTime(17, java.sql.Time.valueOf(doctorRegistrationForm.friTimeStart));
                prestate.setTime(18, java.sql.Time.valueOf(doctorRegistrationForm.friTimeEnd));
                prestate.setTime(19, java.sql.Time.valueOf(doctorRegistrationForm.satTimeStart));
                prestate.setTime(20, java.sql.Time.valueOf(doctorRegistrationForm.satTimeEnd));
                
                prestate.execute();
                JOptionPane.showMessageDialog(null, "Successfully Registered!", "Warning!", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Email or license is already taken.", "Warning!", JOptionPane.INFORMATION_MESSAGE);
                java.util.logging.Logger.getLogger(PanelDoctorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } 
            
        }       
    }//GEN-LAST:event_btnSubmitDoctorRegActionPerformed
    
    public static void CreateTable(String args) {
        String url = "jdbc:mysql://localhost:3306/healthswift?zeroDateTimeBehavior=CONVERT_TO_NULL";
        String username = "root";
        String password = "password";

        try {
            // Establish connection to the MySQL database
            Connection connection = DriverManager.getConnection(url, username, password);

            // Take table name input from user
            String tableName = args;

            // Construct SQL query string dynamically with user-provided table name
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "License already exists!", "Warning!", JOptionPane.INFORMATION_MESSAGE);
            e.printStackTrace();
        } 
    }
    
    private void txtEnterDoctorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterDoctorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterDoctorEmailActionPerformed

    private void btnBackToSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToSignInActionPerformed
        HealthSwift.pnlPatientRegistration.setVisible(false);
        HealthSwift.pnlDoctorRegistration.setVisible(false);
        HealthSwift.pnlSignIn.setVisible(true);
        HealthSwift.animationPanel.setVisible(true);
    }//GEN-LAST:event_btnBackToSignInActionPerformed

    private void txtStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartTimeActionPerformed

    }//GEN-LAST:event_txtStartTimeActionPerformed

    private void txtStartTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStartTimeMouseClicked
        txtStartTime.setText(timePicker.getSelectedTime().substring(0, timePicker.getSelectedTime().length() - 3) + ":00");
    }//GEN-LAST:event_txtStartTimeMouseClicked

    private void txtEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndTimeActionPerformed
        
    }//GEN-LAST:event_txtEndTimeActionPerformed

    private void txtEndTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEndTimeMouseClicked
        txtEndTime.setText(timePicker.getSelectedTime().substring(0, timePicker.getSelectedTime().length() - 3) + ":00");
    }//GEN-LAST:event_txtEndTimeMouseClicked

    private void btnSetSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetSchedActionPerformed
       
        if (txtStartTime.getText().equals("") || txtEndTime.getText().equals("") || txtStartTime.getText().equals(txtEndTime.getText())) {
            JOptionPane.showMessageDialog(null, "Please enter proper time.", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        } else if (Integer.parseInt(txtStartTime.getText().substring(0, 2)) >= Integer.parseInt(txtEndTime.getText().substring(0, 2)) ){
            JOptionPane.showMessageDialog(null, "Please enter valid time.", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtDayReg.getSelectedItem().toString().equals("Monday")) {
            lblMonTime.setText(txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00" + "-" + txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00");
            doctorRegistrationForm.monTimeStart = txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00";
            doctorRegistrationForm.monTimeEnd = txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00";
        } else if (txtDayReg.getSelectedItem().toString().equals("Tuesday")) {
            lblTueTime.setText(txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00" + "-" + txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00");
            doctorRegistrationForm.tueTimeStart = txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00";
            doctorRegistrationForm.tueTimeEnd = txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00";
        } else if (txtDayReg.getSelectedItem().toString().equals("Wednesday")) {
            lblWedTime.setText(txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00" + "-" + txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00");
            doctorRegistrationForm.wedTimeStart = txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00";
            doctorRegistrationForm.wedTimeEnd = txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00";
        } else if (txtDayReg.getSelectedItem().toString().equals("Thursday")) {
            lblThurTime.setText(txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00" + "-" + txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00");
            doctorRegistrationForm.thurTimeStart = txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00";
            doctorRegistrationForm.thurTimeEnd = txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00";
        } else if (txtDayReg.getSelectedItem().toString().equals("Friday")) {
            lblFriTime.setText(txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00" + "-" + txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00");
            doctorRegistrationForm.friTimeStart = txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00";
            doctorRegistrationForm.friTimeEnd = txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00";
        } else if (txtDayReg.getSelectedItem().toString().equals("Saturday")) {
            lblSatTime.setText(txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00" + "-" + txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00");
            doctorRegistrationForm.satTimeStart = txtStartTime.getText().substring(0, txtStartTime.getText().length() - 3) + ":00";
            doctorRegistrationForm.satTimeEnd = txtEndTime.getText().substring(0, txtEndTime.getText().length() - 3) + ":00";
        }
    }//GEN-LAST:event_btnSetSchedActionPerformed

    private void txtDayRegItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtDayRegItemStateChanged
        txtStartTime.setText("");
        txtEndTime.setText("");
    }//GEN-LAST:event_txtDayRegItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnBackToSignIn;
    private javax.swing.JButton btnSetSched;
    private javax.swing.JButton btnSubmitDoctorReg;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblFriTime;
    private javax.swing.JLabel lblMonTime;
    private javax.swing.JLabel lblSatTime;
    private javax.swing.JLabel lblThurTime;
    private javax.swing.JLabel lblTueTime;
    private javax.swing.JLabel lblWedTime;
    private javax.swing.JPanel pnlSignIn;
    private com.raven.swing.TimePicker timePicker;
    private javax.swing.JComboBox<String> txtDayReg;
    private javax.swing.JComboBox<String> txtDocGender;
    private javax.swing.JComboBox<String> txtDoctorSpecialty;
    private javax.swing.JTextField txtEndTime;
    protected static javax.swing.JTextField txtEnterDoctorBDate;
    protected static javax.swing.JTextField txtEnterDoctorEmail;
    protected static javax.swing.JTextField txtEnterDoctorFName;
    protected static javax.swing.JTextField txtEnterDoctorLName;
    private javax.swing.JTextField txtEnterDoctorNo;
    protected static javax.swing.JTextField txtEnterDoctorPassword;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtStartTime;
    // End of variables declaration//GEN-END:variables
}
